[package]
name = "recapn-channel"
version = "0.0.0"
authors = ["Sydney Acksman <obsidianminor@gmail.com>"]
edition = "2021"

[dependencies]
pin-project.workspace = true
parking_lot.workspace = true
hashbrown.workspace = true
scopeguard.workspace = true

[dev-dependencies]
tokio.workspace = true
tokio-test.workspace = true
assert_matches2.workspace = true

[lints]
workspace = true
