[package]
name = "recapn-rpc"
version = "0.0.0"
authors = ["Sydney Acksman <obsidianminor@gmail.com>"]
edition = "2024"

[dependencies]
recapn = { path = "../recapn" }
recapn-channel = { path = "../recapn-channel" }
pin-project.workspace = true
parking_lot.workspace = true
hashbrown.workspace = true
fnv = "1.0"

[dependencies.tokio]
workspace = true
features = ["rt", "macros", "sync"]

[lints]
workspace = true
